name: Greetings
on: [ pull_request, issues ]
jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/first-interaction@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          pr-message: 'Hello @${{ github.actor }}, thank you for submitting a pull request!'
          issue-message: |
            Hello @${{ github.actor }}, thank you for your interest in our work!
            If this is a bug report, please provide screenshots and **minimum viable code to reproduce your issue**, otherwise we can not help you.
